pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/akhilkumar0024/pipeline-ci-demo.git']])
            }
        }
        // stage('Build'){
        //     steps{
        //         dir('pipeline-ci-demo/pipeline-ci-demo') {
        //         sh 'ls'
        //         sh 'mvn clean compile'
        //     }
            
        // }
        // }
        stage('Debug') {
            steps {
                sh '''
                pwd 
                echo "===== Workspace ====="
                find . -maxdepth 4
                '''
            }
        }
        stage('Test'){
            steps{
                sh "mvn test"
            }
        }
        stage('Package'){
            steps{
                sh "mvn package"
            }
        }
    }
}